class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      // Auth / Login
      'app_title': 'Hệ thống Quản lý Đồ án',
      'university_name': 'TRƯỜNG ĐẠI HỌC CÔNG THƯƠNG TP.HCM',
      'system_subtitle': 'HỆ THỐNG ĐĂNG KÝ ĐỒ ÁN - KHÓA LUẬN',
      'username_hint': 'Mã số SV / Mã cán bộ',
      'password_hint': 'Nhập mật khẩu',
      'remember_me': 'Ghi nhớ mật khẩu',
      'forgot_password': 'Quên mật khẩu?',
      'login_button': 'ĐĂNG NHẬP',
      'or_login_with': 'Hoặc đăng nhập bằng',
      'username_empty': 'Vui lòng nhập Mã số SV hoặc Tên đăng nhập!',
      'password_empty': 'Vui lòng nhập Mật khẩu!',
      'login_success': 'Đăng nhập thành công!',
      'copyright': '© 2026 HUIT. All rights reserved.',
      'language_vi': 'Tiếng Việt',
      'language_en': 'English',
      'lang_code_vi': 'VI',
      'lang_code_en': 'EN',

      // Navigation
      'nav_home': 'Trang chủ',
      'nav_schedule': 'Lịch tiến độ',
      'nav_profile': 'Cá nhân',

      // Home Screen
      'main_functions': 'Chức năng chính',
      'view_group': 'Xem nhóm',
      'create_invite_group': 'Tạo / Mời nhóm',
      'register_topic': 'Đăng ký đề tài',
      'role_student': 'Sinh viên',
      'role_lecturer': 'Giảng viên',
      'role_manager': 'Quản lý',

      // Schedule Screen
      'schedule_title': 'Lịch tiến độ khóa luận',
      'current_week': 'Tuần hiện tại',
      'weekly_tasks': 'Nhiệm vụ theo tuần',
      'defense_schedule': 'Lịch bảo vệ hội đồng',
      'defense_official': 'Lịch bảo vệ chính thức',
      'not_published': 'Khoa chưa công bố lịch bảo vệ.',
      'waiting_confirmation': 'Chờ duyệt / xác nhận',

      // Profile Screen
      'profile_title': 'HỒ SƠ CÁ NHÂN',
      'student_info': 'THÔNG TIN SINH VIÊN',
      'full_name': 'Họ và tên',
      'student_id': 'Mã số sinh viên (MSSV)',
      'major': 'Chuyên ngành',
      'class_name': 'Lớp học',
      'email': 'Email sinh viên',
      'phone': 'Số điện thoại',
      'status': 'Trạng thái',
      'status_active': 'Đang học / Đủ ĐK khóa luận',
      'logout': 'Đăng xuất',
      'confirm_logout': 'Bạn có chắc chắn muốn đăng xuất không?',
      'cancel': 'Hủy',
      'confirm': 'Xác nhận',

      // Group List Screen
      'group_list_title': 'DANH SÁCH NHÓM KHÓA LUẬN',
      'group_search_hint': 'Tìm theo tên nhóm, trưởng nhóm...',
      'tab_all': 'Tất cả',
      'tab_recruiting': 'Đang tuyển',
      'tab_full': 'Đã đủ',
      'status_all': 'Tất cả trạng thái',
      'status_recruiting_filter': 'Đang tuyển',
      'status_full_filter': 'Đã đủ',
      'group_leader': 'Nhóm trưởng',
      'group_contact': 'Liên hệ',
      'group_major': 'Chuyên ngành',
      'group_members': 'Thành viên',
      'group_topic': 'Đề tài dự kiến',
      'btn_join_group': 'XIN VÀO NHÓM',
      'btn_requested': 'ĐÃ GỬI YÊU CẦU',
      'btn_full': 'ĐÃ ĐỦ THÀNH VIÊN',
      'join_request_title': 'Gửi yêu cầu tham gia nhóm',
      'join_request_note_hint': 'Nhập lời nhắn gửi đến trưởng nhóm (không bắt buộc)...',
      'join_request_success': 'Đã gửi yêu cầu tham gia nhóm thành công!',
      'join_request_cancelled': 'Đã hủy yêu cầu tham gia nhóm.',
      'filter_all_majors': 'Tất cả ngành',
      'group_details': 'Chi tiết nhóm',
      'no_groups_found': 'Không tìm thấy nhóm phù hợp',

      // Create & Manage Group Screen
      'create_group_title': 'TẠO NHÓM KHÓA LUẬN',
      'create_group_subtitle': 'Đăng ký nhóm mới và trở thành Trưởng nhóm',
      'group_name_label': 'Tên nhóm khóa luận',
      'group_name_hint': 'Ví dụ: Nhóm Nghiên cứu Mobile App Flutter',
      'group_major_select': 'Chuyên ngành nghiên cứu',
      'leader_phone_label': 'Số điện thoại liên lạc của Trưởng nhóm',
      'leader_phone_hint': 'Nhập số điện thoại liên lạc...',
      'btn_create_group': 'TẠO NHÓM NGAY',
      'create_group_success': 'Tạo nhóm khóa luận thành công!',
      'my_group_title': 'QUẢN LÝ NHÓM CỦA TÔI',
      'tab_my_members': 'Thành viên trong nhóm',
      'tab_join_requests': 'Yêu cầu xin vào',
      'btn_invite_member': '+ MỜI THÀNH VIÊN MỚI',
      'btn_approve': 'DUYỆT',
      'btn_reject': 'TỪ CHỐI',
      'approve_request_success': 'Đã duyệt thành viên vào nhóm thành công!',
      'reject_request_success': 'Đã từ chối yêu cầu tham gia.',
      'btn_remove_member': 'Xóa khỏi nhóm',
      'remove_member_confirm': 'Bạn có chắc chắn muốn xóa thành viên này khỏi nhóm?',
      'remove_member_success': 'Đã xóa thành viên khỏi nhóm.',
      'invite_modal_title': 'Mời bạn học vào nhóm',
      'invite_search_hint': 'Tìm theo MSSV hoặc Họ tên...',
      'btn_send_invite': 'MỜI',
      'btn_cancel_invite': 'HỦY MỜI',
      'invite_success': 'Đã gửi lời mời tham gia nhóm!',
      // Topic Registration Screen
      'topic_list_title': 'ĐĂNG KÝ ĐỀ TÀI',
      'topic_search_hint': 'Tìm theo tên đề tài, GVHD, mã đề tài...',
      'topic_details': 'Chi tiết đề tài',
      'btn_register_topic': 'ĐĂNG KÝ',
      'btn_cancel_topic': 'HỦY ĐĂNG KÝ',
      'btn_propose_topic': 'Đề xuất đề tài mới',
      'topic_registered_success': 'Đăng ký đề tài thành công!',
      'topic_cancelled_success': 'Đã hủy đăng ký đề tài thành công!',
    },
    'en': {
      // Auth / Login
      'app_title': 'Thesis Management System',
      'university_name': 'HO CHI MINH CITY UNIVERSITY OF INDUSTRY AND TRADE',
      'system_subtitle': 'GRADUATION THESIS & PROJECT REGISTRATION SYSTEM',
      'username_hint': 'Student ID / Staff Code',
      'password_hint': 'Enter password',
      'remember_me': 'Remember password',
      'forgot_password': 'Forgot password?',
      'login_button': 'SIGN IN',
      'or_login_with': 'Or sign in with',
      'username_empty': 'Please enter Student ID or Username!',
      'password_empty': 'Please enter Password!',
      'login_success': 'Signed in successfully!',
      'copyright': '© 2026 HUIT. All rights reserved.',
      'language_vi': 'Tiếng Việt',
      'language_en': 'English',
      'lang_code_vi': 'VI',
      'lang_code_en': 'EN',

      // Navigation
      'nav_home': 'Home',
      'nav_schedule': 'Schedule',
      'nav_profile': 'Profile',

      // Home Screen
      'main_functions': 'Main Functions',
      'view_group': 'View Group',
      'create_invite_group': 'Create / Invite',
      'register_topic': 'Register Topic',
      'role_student': 'Student',
      'role_lecturer': 'Lecturer',
      'role_manager': 'Manager',

      // Schedule Screen
      'schedule_title': 'Thesis Progress Schedule',
      'current_week': 'Current Week',
      'weekly_tasks': 'Weekly Tasks',
      'defense_schedule': 'Defense Committee Schedule',
      'defense_official': 'Official Defense Schedule',
      'not_published': 'Faculty has not published the defense schedule yet.',
      'waiting_confirmation': 'Pending review / confirmation',

      // Profile Screen
      'profile_title': 'USER PROFILE',
      'student_info': 'STUDENT INFORMATION',
      'full_name': 'Full Name',
      'student_id': 'Student ID',
      'major': 'Major',
      'class_name': 'Class',
      'email': 'Email',
      'phone': 'Phone Number',
      'status': 'Status',
      'status_active': 'Enrolled / Eligible for thesis',
      'logout': 'Sign Out',
      'confirm_logout': 'Are you sure you want to sign out?',
      'cancel': 'Cancel',
      'confirm': 'Confirm',

      // Group List Screen
      'group_list_title': 'THESIS GROUPS LIST',
      'group_search_hint': 'Search by group name, leader...',
      'tab_all': 'All',
      'tab_recruiting': 'Recruiting',
      'tab_full': 'Full',
      'status_all': 'All Status',
      'status_recruiting_filter': 'Recruiting',
      'status_full_filter': 'Full',
      'group_leader': 'Group Leader',
      'group_contact': 'Contact',
      'group_major': 'Specialization',
      'group_members': 'Members',
      'group_topic': 'Topic',
      'btn_join_group': 'JOIN GROUP',
      'btn_requested': 'REQUESTED',
      'btn_full': 'GROUP FULL',
      'join_request_title': 'Send Join Request',
      'join_request_note_hint': 'Enter note for group leader (optional)...',
      'join_request_success': 'Join request sent successfully!',
      'join_request_cancelled': 'Join request cancelled.',
      'filter_all_majors': 'All Majors',
      'group_details': 'Group Details',
      'no_groups_found': 'No matching groups found',

      // Create & Manage Group Screen
      'create_group_title': 'CREATE THESIS GROUP',
      'create_group_subtitle': 'Register new group and become Group Leader',
      'group_name_label': 'Thesis Group Name',
      'group_name_hint': 'E.g., Flutter Mobile App Research Group',
      'group_major_select': 'Research Specialization',
      'leader_phone_label': 'Group Leader Contact Phone',
      'leader_phone_hint': 'Enter phone number...',
      'btn_create_group': 'CREATE GROUP NOW',
      'create_group_success': 'Thesis group created successfully!',
      'my_group_title': 'MY GROUP MANAGEMENT',
      'tab_my_members': 'Group Members',
      'tab_join_requests': 'Join Requests',
      'btn_invite_member': '+ INVITE NEW MEMBER',
      'btn_approve': 'APPROVE',
      'btn_reject': 'REJECT',
      'approve_request_success': 'Member approved successfully!',
      'reject_request_success': 'Join request rejected.',
      'btn_remove_member': 'Remove from group',
      'remove_member_confirm': 'Are you sure you want to remove this member from group?',
      'remove_member_success': 'Member removed from group.',
      'invite_modal_title': 'Invite Student to Group',
      'invite_search_hint': 'Search by student ID or name...',
      'btn_send_invite': 'INVITE',
      'btn_cancel_invite': 'CANCEL',
      'invite_success': 'Invitation sent successfully!',
      // Topic Registration Screen
      'topic_list_title': 'TOPIC REGISTRATION',
      'topic_search_hint': 'Search by topic name, supervisor, code...',
      'topic_details': 'Topic Details',
      'btn_register_topic': 'REGISTER',
      'btn_cancel_topic': 'CANCEL REGISTRATION',
      'btn_propose_topic': 'Propose New Topic',
      'topic_registered_success': 'Topic registered successfully!',
      'topic_cancelled_success': 'Topic registration cancelled successfully!',
    },
  };

  static String get(String key, {String lang = 'vi'}) {
    return _localizedValues[lang]?[key] ?? _localizedValues['vi']?[key] ?? key;
  }
}
